### ISSUE TITLE
Ajax throwing 404 while trying to load in inspect/media query sizes(1024, 1200, 1400, 1600 px) etc.

### ISSUE THREAD

**Issue by Chandrasekhar1211** [addonify/addonify-quick-view#150] opened 2023-05-03 17:29 UTC
I'm trying to do media query on my website for quick view. While loading popup in inspect, the popup still showing loading icon. not loading instead showing white screen. Here I'm attaching a screenshot below.
![image](https://user-images.githubusercontent.com/106801870/235994613-18cb4978-dc7f-4ef2-aeff-06a9f5e0aaac.png)

**Comment by Asok17** [comment] 2023-05-05 05:27
Hello @Chandrasekhar1211 

Have you enabled debugging on your website? If you have then could you send us the detail of the debug log? It would help us identify the problem and resolve it.

Best regards.

**Comment by Chandrasekhar1211** [comment] 2023-05-05 05:57
Hi @Asok17,
Thank you for your support!
I have enabled the debug mode. I cannot see anything related to the Addonify in debug log. The only 400 issue is coming for addonify popup in the console while checking. Debug kept enabled. You also please check.
![image](https://user-images.githubusercontent.com/106801870/236385224-078db7f8-95d3-4b3d-83ce-5f2a72492c09.png)

And also the special currency symbols which are added in the currency switcher are not calling inside popup. Only coming the default currency symbol($). If we add the special currency symbol in switcher, we are unable to see it in popup. But, coming in PDP.
![image](https://user-images.githubusercontent.com/106801870/236386295-cd9bf48d-1f43-48e3-a190-7c8736b525ab.png)
![image](https://user-images.githubusercontent.com/106801870/236386113-ee75a116-67de-435e-a8b7-d1d7da622cf9.png)

**Comment by Asok17** [comment] 2023-05-10 05:03
Hello @Chandrasekhar1211 

Are you able to solve the issues? 

I did the test to see if 400 error occur for media queries and I found none. The content gets displayed and does not pause on the loader.

About the currency symbol, which plugin are you using for the multi currency? We have hooked `woocommerce_template_single_price` function to display the product price. If it did not work then look how the multi currency has worked to display the currency symbol in PDP.

Best regards.

**Comment by Chandrasekhar1211** [comment] 2023-05-10 09:34
Hi @Asok17 
We are using WooCommerce Multi-currency By [TIV.NET INC](https://profiles.wordpress.org/tivnetinc/). The same hook using to call the pricing on PDP which is using the same in quick view popup. And yes, the issue is still coming. If you go inspect and set the screen width to the 1200 above and click on the button to open the popup. It is throwing like this...
![image](https://github.com/addonify/addonify-quick-view/assets/106801870/fc04fed8-d903-4f86-9bc6-a0f264b0df59)

**Comment by Chandrasekhar1211** [comment] 2023-05-10 09:36
And sometimes, the gallery carousel is getting collapsed like the one below.
![image](https://github.com/addonify/addonify-quick-view/assets/106801870/63d5797b-6efa-442a-bd18-2088cf68aeb3)

Here I'm attaching the screen record videos for your reference.
https://imgur.com/a/BOhPkwL

**Comment by Asok17** [comment] 2023-05-10 12:21
Hello @Chandrasekhar1211 

We have just updated the plugin in this repository. [Download](https://github.com/addonify/addonify-quick-view/archive/refs/heads/development.zip) it and update it on your website. Let me know if the AJAX error is resolved.

I could not find the plugin in [WordPress repository](https://profiles.wordpress.org/tivnetinc/#content-plugins). Is the multi-currency plugin a premium add-on? If no, then send me the link to download it. Else, let me know how I can get it.

About the gallery carousel getting collapsed, check if WooCommerce styles and script are being loaded. When I checked your website, I found that default WooCommerce styles are not there.

Best regards.

**Comment by Chandrasekhar1211** [comment] 2023-05-12 15:44
Hi, @Asok17! 
Yes! The JQuery issue is still coming.
![image](https://github.com/addonify/addonify-quick-view/assets/106801870/5cd934b0-d30d-49e3-aaeb-47413b9f1ca3)

And the multi-currency plugin is the paid one from WooCommerce extensions. Here you can find their WooCommerce profile [here](https://woocommerce.com/document/multi-currency/). One more link: https://woocommerce.com/vendor/tiv-net-inc/. And let me check about the WooCommerce styles loading and update you. One more thing I wanted to know, can I copy the class-addonify-quick-view-public.php file into my child-theme to customize? or do I have to add any new hook/function through the functions.php only?

Regards.

**Comment by Asok17** [comment] 2023-05-14 05:23
@Chandrasekhar1211 

I have tested the plugin on my side. The media query is working fine on my side. 

It is difficult to find what has gone wrong on your side just with the image. So in order to find out more detail on the issue, it would be better if I could get the login credentials of your website's WordPress dashboard. If you are okay with it, please send me the login credentials as addonify@gmail.com.

Best regards.

**Comment by Chandrasekhar1211** [comment] 2023-05-15 07:07
Hi @Asok17! 

Good morning! Yes, I have shared the login details of my staging to the above email ID. Please check and let me know if anything you need.

Thanks & regards.

**Comment by addonify** [comment] 2023-05-16 08:49
Hello @Chandrasekhar1211,

Thank you for sharing the login credentials.

I inspected your website for the issue. When testing the quick view in
media queries, I found no AJAX errors. I have attached the screenshots.
Please find it.

About the price, I need the plugin and find out what has caused the issue.
If you can help me with it, maybe I can help you.

Best regards.

**Comment by Chandrasekhar1211** [comment] 2023-05-16 10:06
Hi, sure. I will share the plugin via mail. And can you share the screenshots of Ajax errors? I can't find the attachments above. And let me know what could be the solution for Ajax errors.

Thanks in advance.

**Comment by Asok17** [comment] 2023-05-16 12:14
Here are the screenshots, [1200](https://prnt.sc/muJ3JaGXUmKE) and [1400](https://prnt.sc/46kydddQx3S3).

Best regards.

**Comment by Chandrasekhar1211** [comment] 2023-05-16 12:23
Hi, the 404 images are replaced. Those are missing files. Can you check now? You will find those missing images but the jquery issue is there. 
![image](https://github.com/addonify/addonify-quick-view/assets/106801870/d5b12e9d-76b2-4188-9c9b-606ef7f27d9c)

**Comment by Asok17** [comment] 2023-05-19 14:22
Hi @Chandrasekhar1211,

We have identified the cause of the AJAX issue and fixed it.

Download the latest code from [here](https://github.com/addonify/addonify-quick-view/archive/refs/heads/development.zip) and upload it.

Let me know if the update does not work.

**Comment by Chandrasekhar1211** [comment] 2023-05-22 11:08
Hi @Asok17, Let me check and update you.

Thank you very much!

**Comment by Asok17** [comment] 2023-05-31 04:33
For now, I am closing this issue. If you, @Chandrasekhar1211,  encounter any issues then create new one.

**Closed as completed by Asok17** 2023-05-31 04:33 UTC
Labels: bug
